// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVIrQ3nx3Nzrb85DI1jlvugLxNfyw9jPQ',
    appId: '1:621856504621:web:dfba379ffbdc989462f1a4',
    messagingSenderId: '621856504621',
    projectId: 'tracksafe-link',
    authDomain: 'tracksafe-link.firebaseapp.com',
    databaseURL: 'https://tracksafe-link-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tracksafe-link.firebasestorage.app',
    measurementId: 'G-86G593DR8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY-Coks6Im14k6ElFP0v9vdMOtOYcFgTk',
    appId: '1:621856504621:android:a63f97fb0b8300a862f1a4',
    messagingSenderId: '621856504621',
    projectId: 'tracksafe-link',
    databaseURL: 'https://tracksafe-link-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tracksafe-link.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVIrQ3nx3Nzrb85DI1jlvugLxNfyw9jPQ',
    appId: '1:621856504621:web:f0d6d23aca88958462f1a4',
    messagingSenderId: '621856504621',
    projectId: 'tracksafe-link',
    authDomain: 'tracksafe-link.firebaseapp.com',
    databaseURL: 'https://tracksafe-link-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tracksafe-link.firebasestorage.app',
    measurementId: 'G-W0G1L1DDK6',
  );
}
